namespace BLL.PropertyClasses.Master
{
    public class Party_MasterProperty
    {
        public int party_id { get; set; }
        public string party_shortname { get; set; }
        public string party_name { get; set; }
        public string init_name { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string party_type { get; set; }
        public string business_type { get; set; }
        public string address { get; set; }
        public string pincode { get; set; }
        public int? city_id { get; set; }
        public int? state_id { get; set; }
        public int? country_id { get; set; }
        public string phone1country { get; set; }
        public string phone1city { get; set; }
        public string phone1 { get; set; }
        public string phone2country { get; set; }
        public string phone2city { get; set; }
        public string phone2 { get; set; }
        public string mobile1country { get; set; }
        public string mobile1 { get; set; }
        public string mobile2country { get; set; }
        public string mobile2 { get; set; }
        public string fax_country { get; set; }
        public string fax_city { get; set; }
        public string fax { get; set; }
        public string website { get; set; }
        public string primary_email { get; set; }
        public string secondary_email { get; set; }
        public double? discount { get; set; }
        public int? on_hold_days { get; set; }
        public bool? allow_online_buy { get; set; }
        public int? category_id { get; set; }
        public string category_update_date { get; set; }
        public string aadhar_no { get; set; }
        public string pancard_no { get; set; }
        public string tds_circle { get; set; }
        public string vat_no { get; set; }
        public string vat_date { get; set; }
        public string gst_no { get; set; }
        public string gst_date { get; set; }
        public string cst_no { get; set; }
        public string cst_date { get; set; }
        public string tan_no { get; set; }
        public string tan_date { get; set; }
        public string service_tax_no { get; set; }
        public string service_tax_date { get; set; }
        public byte[] visiting_card { get; set; }
        public string registration_date { get; set; }
        public string registration_type { get; set; }
        public string registration_source { get; set; }
        public bool? active { get; set; }
        public string approved_date { get; set; }
        public int? approved_by_user_id { get; set; }
        public string approved_ip_address { get; set; }
        public string rapnet_id { get; set; }
        public string idex_id { get; set; }
        public string polygon_id { get; set; }
        public string source { get; set; }
        public string remarks { get; set; }
        public int? sequence_no { get; set; }
        public int? company_id { get; set; }
        public int? branch_id { get; set; }
        public int? location_id { get; set; }
        public int? department_id { get; set; }
        public int? user_id { get; set; }
        public string entry_date { get; set; }
        public string entry_time { get; set; }
        public string ip_address { get; set; }
    }
}
